# Spam eMail Detection

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv('emails.csv')

In [3]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [4]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [5]:
df.drop_duplicates(inplace = True)


In [6]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [7]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [8]:
df.isnull().sum()

text    0
spam    0
dtype: int64

# Seperate x and y

In [9]:
x = df.text.values

In [10]:
y = df.spam.values

In [11]:
y

array([1, 1, 1, ..., 0, 0, 0])

# Split dataset

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2)

# Data Preprocessing

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)
x_train2 = cv.fit_transform(x)

In [16]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# ML Algorithm

In [17]:
from sklearn.naive_bayes import MultinomialNB

In [18]:
model= MultinomialNB()

In [19]:
model.fit(x_train,ytrain)

MultinomialNB()

In [20]:
ytrain

array([0, 0, 0, ..., 0, 0, 0])

In [21]:
x_train.toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# K-Fold Cross validation

In [22]:
from sklearn.model_selection import cross_val_score

In [23]:
cv_score = cross_val_score(model,x_train2,y,cv=10)

In [24]:
cv_score

array([0.98421053, 0.99122807, 0.98947368, 0.99122807, 0.99649123,
       0.98418278, 0.98242531, 0.99297012, 0.98945518, 0.99121265])